# Generated by Django 3.2.3 on 2021-05-29 11:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('licensePlate', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63)),
                ('comments', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 5, 29, 11, 6, 29, 153244, tzinfo=utc))),
                ('car', models.ForeignKey(db_column='car_licensePlate', null=True, on_delete=django.db.models.deletion.PROTECT, to='kmrecord.car')),
            ],
        ),
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kmrecord.record')),
                ('fuelType', models.SmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=7)),
                ('pricePerLitre', models.DecimalField(decimal_places=3, max_digits=5)),
                ('gasStation', models.CharField(max_length=63)),
            ],
            bases=('kmrecord.record',),
        ),
        migrations.CreateModel(
            name='RichRecord',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kmrecord.record')),
                ('comments', models.CharField(max_length=255)),
            ],
            bases=('kmrecord.record',),
        ),
    ]
