# Generated by Django 3.2.3 on 2021-05-29 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kmrecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 11, 47, 22, 417071, tzinfo=utc)),
        ),
    ]
