# Generated by Django 3.2.3 on 2021-06-02 06:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kmrecord', '0002_alter_record_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelrecord',
            name='record_ptr',
        ),
        migrations.RemoveField(
            model_name='richrecord',
            name='record_ptr',
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='record',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kmrecord.record'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='richrecord',
            name='record',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kmrecord.record'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 6, 56, 23, 200986, tzinfo=utc)),
        ),
    ]
