# Generated by Django 3.2.3 on 2021-06-04 07:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kmrecord', '0004_auto_20210602_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 4, 7, 7, 57, 263075, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fuelrecord',
            name='gasStation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kmrecord.gasstation'),
        ),
    ]
